/*THIS IS NOT A CODE. IT'S ONLY MY FIRST GITHUB PROJECT PUBLISHED DIRECTLY FROM VISUAL STUDIO CODE

GREETINGS TO LOS CURIFEOS, SDLG, BAJOSABLE_YT, SOYTAE, BELCHIKITA, AZUNALAND AND FINALLY TO MARIN KITAGAWA, NINO NAKANO AND KTACCINO MY BELOVED

THANKS TO TECHWEBDOCS*/


int main()
{
    /*xd*/
}